# 编程语言及版本: Python 3.7.3
# 编辑器及版本: Vi IMproved 8.1
# 操作系统: Manjaro 18.0.4

all:
	python3 main.py > MonChefDoeuvre1194.py

install:
	sudo pip3 install -r requirements.txt
	sudo pacman -S potrace  # http://potrace.sourceforge.net/